### PR TITLE
Paebbels/master

### PR DESCRIPTION
**Pull request by Paebbels**
So here are the windows compile files for the vendor libraries (Altera, Xilinx and OSVVM). A README is included, so it's visible by browsing the GitHub source tree.

ToDo:
 - translate to bash syntax
 - support for vunit by @LarsAsplund and @kraigher

Planned improvements:
 - add embedded documentation for the PoSh scripts, so `man` can extract the help from the scripts
 - common setup script, which is sourced by all vendor scripts => easier configuration
 - extract the error checking and reporting functionality into a function

Open Questions:
 - is it possible to find the installation directory automatically?

### CODE REVIEW

**Comment by tgingold** [comment]
compile-osvvm.ps1 is empty.  Is it expected ?

**Comment by Paebbels** [comment]
That was not my intension …

Strange: the file on disk has 5 kiB, but SourceTree commited an empty file …

 

Ah I found it …

GitHub recognizes this file as binary, so no diff is shown:

https://github.com/Paebbels/ghdl/blob/49328bb4f2681af5c2d6a8378d76aefdfca3f28c/libraries/vendors/compile-osvvm.ps1

 

 

-----------------------------------

Wissenschaftliche Hilfskraft

 

Technische Universität Dresden

Fakultät Informatik

Institut für Technische Informatik

Lehrstuhl VLSI-Entwurfssysteme, Diagnostik und Architektur

01062 Dresden

Tel.:   +49 351 463-38451

Fax:    +49 351 463-38324

Raum:   APB-1020

E-Mail:  <mailto:Patrick.Lehmann@tu-dresden.de> Patrick.Lehmann@tu-dresden.de

WWW:     <http://vlsi-eda.inf.tu-dresden.de/> http://vlsi-eda.inf.tu-dresden.de

**Comment by Paebbels** [comment]
Nice, GitHub noticed 3 new commits and assigned them to #1.
The strange behavior of stderr was outsourced as a [stackoverflow question] ...(http://stackoverflow.com/questions/33838633/why-does-powershell-chops-message-on-stderr)

**Comment by tgingold** [comment]
For compile-osvvm, github recognise the file as binary because it is in UTF-16.
Can you convert it to ascii ?  And that would be ok for the merge.

Thanks!

**Comment by Paebbels** [comment]
So, the compile-osvvm.ps1 file is UTF-8 encoded (no BOM). I wrote a CommandLet to reformat the warnings and error messages from ghdl. They are now emitted as one object per line. [StackOverflow discussion](http://stackoverflow.com/questions/33838633/why-does-powershell-chops-message-on-stderr)

Xilinx ISE and Xilinx Vivado have a different folder structure and library set, so I split the file into two.

I got the VUnit compile order from @LarsAsplund. So it's also included as a script.

**Comment by Paebbels** [comment]
Added file headers as agreed. Is
```
#	Copyright (C) 2002, 2003, 2004, 2005 Tristan Gingold
```
still correct in new files, because it's already 2015?

**Comment by Paebbels** [comment]
So the embedded help pages can now be printed with:
```
PS> Get-Help <script.ps1> [-Detailed]
```

**Comment by tgingold** [comment]
On 23/11/15 22:50, Patrick Lehmann wrote:
> Added file headers as agreed. Is
>
> |# Copyright (C) 2002, 2003, 2004, 2005 Tristan Gingold |
>
> still correct in new files, because it's already 2015?

No, that should be Copyright (C) 2015 Patrick Lehmann

Tristan.

**Comment by tgingold** [comment]
On 23/11/15 23:23, Patrick Lehmann wrote:
> So the embedded help pages can now be printed with:
>
> |PS> Get-Help <script.ps1> [-Detailed] |

Nice.

**Comment by tgingold** [comment]
Squashed and merged.

I deleted trailing blanks in README.md

Thank you!

**Pull request closed without merging**
