### PR TITLE
Get documentation version from latest Git tag.

### PR DESCRIPTION
**Pull request by Paebbels**
This pull requests changes:
* Extract the latest GHDL version from Git tags and use it as documentation version.
* If GHDL is not in a Git environment (e.g. ZIP download) it defaults to the hard encoded value.

### CODE REVIEW

**Comment by tgingold** [comment]
I think the default should be extracted from ../src/version.in

**Comment by Paebbels** [comment]
Can you write a TODO and assign it to my account?

**Comment by tgingold** [comment]
On 11/12/16 07:29, Patrick Lehmann wrote:
> Can you write a TODO and assign it to my account?

Do you mean create a new issue and assign it to you ?

**Comment by Paebbels** [comment]
Yes.

I'll add the code to read the version number from `src\version.in` in the next weeks. Otherwise I might forget this task :).

**Comment by tgingold** [comment]
On 11/12/16 07:46, Patrick Lehmann wrote:
> Yes.
>
> I'll add the code to read the version number from |src\version.in| in
> the next weeks. Otherwise I might forget this task :).

I created it (#221) but I cannot assign it to you.  I think you should 
at last make a comment on that issue.

**Comment by Paebbels** [comment]
May me I need to be registered as a GHDL collaborator (currently contributor).
This can be configured in GitHub as follows:
image

**Comment by Paebbels** [comment]
Is it now assignable?

**Comment by tgingold** [comment]
On 11/12/16 08:05, Patrick Lehmann wrote:
> Is it now assignable?

yes and assigned.

**Comment by 1138-4EB** [comment]
I added PR #287, which fixes #221, i.e., defaults to reading `../src/version.in`.

However I think that retrieving the latest tag is not the best now: since there is no `0.34-dev`, version `0.33` is shown. Even if we modify it now, according to #280, it will still display `0.33`.  Should a rolling `0.34-dev` tag be created? The, it would be renamed to `0.34` when changing to `0.35-dev`. I can take this into account when implementing 'nightly builds', so that the `*-dev` tag is updated with the last successful build each day. What do you think?

**Comment by tgingold** [comment]
On 18/02/17 05:22, 1138-4EB wrote:
> I added PR #287 <https://github.com/tgingold/ghdl/pull/287>, which fixes
> #221 <https://github.com/tgingold/ghdl/issues/221>, i.e., defaults to
> reading |../src/version.in|.
>
> However I think that retrieving the latest tag is not the best now:
> since there is no |0.34-dev|, version |0.33| is shown. Even if we modify
> it now, according to #280 <https://github.com/tgingold/ghdl/issues/280>,
> it will still display |0.33|. Should a rolling |0.34-dev| tag be
> created? The, it would be renamed to |0.34| when changing to |0.35-dev|.
> I can take this into account when implementing 'nightly builds', so that
> the |*-dev| tag is updated with the last successful build each day. What
> do you think?

But, I get:

$ git describe --abbrev=0 --tags
2016-09-14


According to git describe --help:

If the tag points to the commit, then only the tag is shown. Otherwise,
it suffixes the tag name with the number of additional commits on top
of the tagged object and the abbreviated object name of the most recent
commit.


... which looks good to me.
There is no 0.33 tag.  To build the 0.33 release, I have just created a 
branch.

How did you get 0.33 ?

**Comment by 1138-4EB** [comment]
I think that the piece of code you are referring to is what @Paebbels contributed. It is already merged and workin. I don't know exactly how, but check the title of http://ghdl.readthedocs.io/en/latest/.

My contribution is to add an `else` clause. Check lines 70-76 [here](https://github.com/tgingold/ghdl/pull/287/files). That is, I read `../src/version.in`, I didn't change that part.

**Comment by tgingold** [comment]
On 18/02/17 06:03, 1138-4EB wrote:
> I think that the piece of code you are referring to is what @Paebbels
> <https://github.com/Paebbels> contributed. It is already merged and
> workin. I don't know exactly how, but check the title of
> http://ghdl.readthedocs.io/en/latest/.
>
> My contribution is to add an |else| clause. Check lines 70-76 here
> <https://github.com/tgingold/ghdl/pull/287/files>. That is, I read
> |../src/version.in|, I didn't change that part.

I suppose that when the doc is built by RTD, it isn't under a git repo.
(To be confirmed from the doc of RTD ?)

So, _IsUnderGitControl is false, and version/release are statically set 
to 0.33
With your patch, they will be extracted from version.in, which is much 
better.

But I didn't understand your previous message.  Why did you say:
 > However I think that retrieving the latest tag is not the best now: 
since there is no 0.34-dev, version 0.33 is shown.

Tristan.

**Comment by 1138-4EB** [comment]
If you check  http://ghdl.readthedocs.io/en/latest/, you see `0.33` in the title. Maybe tomorrow or next week we will update the doc, and that won't change since there will be no new releases nor tags. Therefore, some of the features described in the updated doc may not match the title.

A possible workaround is to make a new tag now, so that `latest` points to it.

Ideally, you could activate the `v0.33` branch in readthedocs, so that it is stick to the actual content. However, that would require to take `doc` as it is now, copy it to branch v0.33 and make a commit there.

**Comment by tgingold** [comment]
On 18/02/17 06:20, 1138-4EB wrote:
> If you check http://ghdl.readthedocs.io/en/latest/, you see |0.33| in
> the title. Maybe tomorrow or next week we will update the doc, and that
> won't change since there will be no new releases nor tags. Therefore,
> some of the features described in the updated doc may not match the title.

Let's merge your patch and check the new title.

**Comment by Paebbels** [comment]
@tgingold wrote:
> I suppose that when the doc is built by RTD, it isn't under a git repo.

My experiments show that the repo is fully checked out and resides in a git controlled directory. Each build-event triggers a `git pull` command. I noticed that temporary files are still present on a new RTD build! Each branch resides in an own directory, which is a full git checkout. Maybe it's possible to checkout different branches into different working directories by using only one underlying Git repo. However, I had big problems in removing temp files, which some Sphinx addons create and thus are not overwritten if they still exist on a new build...

**Comment by tgingold** [comment]
On 18/02/17 06:38, Patrick Lehmann wrote:
> @tgingold <https://github.com/tgingold> wrote:
>
>     I suppose that when the doc is built by RTD, it isn't under a git repo.
>
> My experiments show that the repo is fully checked out and resides in a
> git controlled directory. Each build-event triggers a |git pull|
> command. I noticed that temporary files are still present on a new RTD
> build! Each branch resides in an own directory, which is a full git
> checkout. Maybe it's possible to checkout different branches into
> different working directories by using only one underlying Git repo.
> However, I had big problems in removing temp files, which some Sphinx
> addons create and thus are not overwritten if they still exist on a new
> build...

Doc builds now fail in RTD.

So I think python is not run in the doc/ directory.

**Comment by 1138-4EB** [comment]
My fault. Move `version="latest"` to line 63.

**Comment by tgingold** [comment]
On 18/02/17 06:45, 1138-4EB wrote:
> My fault. Move |version="latest"| to line 63.

It is now Ok.

But I don't understand why it cannot read version.in

**Comment by 1138-4EB** [comment]
Maybe this little trick will let us know: `version=os.path`.

**Comment by tgingold** [comment]
On 18/02/17 06:55, 1138-4EB wrote:
> Maybe this little trick will let us know: |version=os.path|.

Arghh:

making output directory...
file:/home/docs/checkouts/readthedocs.org/user_builds/ghdl/checkouts/latest/doc/conf.py
cwd:/home/docs/checkouts/readthedocs.org/user_builds/ghdl/checkouts/latest/doc

Puzzling.

**Comment by Paebbels** [comment]
Yes. RTD moves the working directory after git checkout / git pull into the docs directory, wherever it finds one.

**Comment by 1138-4EB** [comment]
Check this: `version = os.listdir("../src")`.

**Comment by tgingold** [comment]
On 18/02/17 07:13, 1138-4EB wrote:
> Check this: |version = os.listdir("../src")|.

I think this is now fixed.
We are now using the last tag, which may not be correct.

**Pull request merged**
