### PR TITLE
This fixes issue #213.

### PR DESCRIPTION
**Pull request by Paebbels**
See explanations by @mzabeltud.

### CODE REVIEW

**Comment by tgingold** [comment]
I think that relocPic should be selected only if needed.  Configure should check if gcc was configured with --enable-default-pie

**Comment by Paebbels** [comment]
Hmmm the Windows GCC platforms (MinGW32, MinGW64, any other?) won't support PIC, because it's Linux specific, right? As far as we found out, PIC is supported by GCC since 4.9 (I have no older version to check it). Only the default seams to be changed since 6.2.

Is PIC a bad feature or performance killer, so it shouldn't be enabled by default?

-----------------
Distribution list: @mzabeltud

**Comment by tgingold** [comment]
On 05/12/16 20:51, Patrick Lehmann wrote:
> Hmmm the Windows GCC platforms (MinGW32, MinGW64, any other?) won't
> support PIC, because it's Linux specific, right? As far as we found out,
> PIC is supported by GCC since 4.9 (I have no older version to check it).

I think -fpic/-fPIC is available for much longer, and on almost all 
platforms.

> Only the default seams to be changed since 6.2.

Indeed, and possibly only on debian.

> Is PIC a bad feature or performance killer, so it shouldn't be enabled
> by default?

Not a performance killer, but I prefer to enable it only when needed.
I am testing a patch.  Don't worry!

**Comment by tgingold** [comment]
Should now be fixed (at least with llvm backend).

**Pull request closed without merging**
